#!/usr/bin/env python3
"""
gen_cjk_16x16.py  –  Generate 16×16 CJK bitmaps for ESP32 LCD (ST7735S)

16×16 is the classic minimum size for legible Chinese characters.
Renders at 4× oversampling (64px) with SimHei bold font.

Usage:
    python gen_cjk_12x12.py            # writes main/char_bitmap.h
    python gen_cjk_12x12.py --preview  # also prints ASCII art of each char
"""

import os, sys, argparse

try:
    from PIL import Image, ImageDraw, ImageFont, ImageFilter
except ImportError:
    import subprocess
    print("Pillow not found – installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow", "-q"])
    from PIL import Image, ImageDraw, ImageFont, ImageFilter

# ── characters ───────────────────────────────────────────────────────────────
CHARACTERS = [
    ('气', 0x6C14, 'qi',     'Air/Gas'),
    ('温', 0x6E29, 'wen',    'Temperature'),
    ('湿', 0x6E7F, 'shi',    'Humidity'),
    ('度', 0x5EA6, 'du',     'Degree'),
    ('土', 0x571F, 'tu',     'Soil/Ground'),
    ('光', 0x5149, 'guang',  'Light'),
    ('照', 0x7167, 'zhao',   'Illuminate'),
    ('压', 0x538B, 'ya',     'Pressure'),
    ('等', 0x7B49, 'deng',   'Etc./Wait'),
    ('待', 0x5F85, 'dai',    'Wait'),
    ('无', 0x65E0, 'wu',     'None/No'),
    ('数', 0x6570, 'shu',    'Number'),
    ('据', 0x636E, 'ju',     'Data/According'),
    ('中', 0x4E2D, 'zhong',  'Middle/In'),
]

OUT_SIZE   = 16    # final bitmap dimension — classic CJK minimum
OVER_SIZE  = 160   # render size (10× oversampling for stroke preservation)
THRESHOLD  = 180   # grayscale threshold (higher = preserve more thin strokes)

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\simhei.ttf",    # SimHei (bold, best for small sizes)
    r"C:\Windows\Fonts\msyhbd.ttc",    # Microsoft YaHei Bold
    r"C:\Windows\Fonts\msyh.ttc",      # Microsoft YaHei
    r"C:\Windows\Fonts\simsun.ttc",    # SimSun
    r"C:\Windows\Fonts\NSimSun.ttf",
    "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
    "/System/Library/Fonts/PingFang.ttc",
]

def find_font():
    for p in FONT_CANDIDATES:
        if os.path.isfile(p):
            return p
    return None

def render_char(char, font, thr=THRESHOLD):
    big = Image.new('L', (OVER_SIZE, OVER_SIZE), 255)
    d = ImageDraw.Draw(big)
    left, top, right, bottom = d.textbbox((0, 0), char, font=font)
    tw, th = right - left, bottom - top
    ox = (OVER_SIZE - tw) // 2 - left
    oy = (OVER_SIZE - th) // 2 - top
    d.text((ox, oy), char, font=font, fill=0)

    # Dilate strokes at high-res to prevent thin-stroke loss during downscale
    # MinFilter(3) expands dark pixels by ~1px at 160×160
    big = big.filter(ImageFilter.MinFilter(3))

    # BOX filter = clean area average, no LANCZOS ringing artifacts
    small = big.resize((OUT_SIZE, OUT_SIZE), Image.BOX)
    small = small.point(lambda v: 0 if v < thr else 255, '1')
    return small

def img_to_uint16_rows(img):
    px = list(img.getdata())
    rows = []
    for r in range(OUT_SIZE):
        v = 0
        for c in range(OUT_SIZE):
            bit = 1 if px[r * OUT_SIZE + c] == 0 else 0
            v |= bit << (15 - c)
        rows.append(v)
    return rows

def ascii_preview(img, char):
    px = list(img.getdata())
    lines = [f"  {char}  ({OUT_SIZE}×{OUT_SIZE} preview):"]
    lines.append("  +" + "-" * OUT_SIZE + "+")
    for r in range(OUT_SIZE):
        row_str = ""
        for c in range(OUT_SIZE):
            row_str += "█" if px[r * OUT_SIZE + c] == 0 else "·"
        lines.append("  |" + row_str + "|")
    lines.append("  +" + "-" * OUT_SIZE + "+")
    return "\n".join(lines)

HEADER_TEMPLATE = """\
#ifndef CHAR_BITMAP_H
#define CHAR_BITMAP_H

#include <stdint.h>

// Chinese character bitmaps (16×16 pixels)
// Generated by gen_cjk_12x12.py from font: {font_name}
//
// Format: uint16_t[16] per character
//   bit 15 = leftmost pixel, bit 0 = rightmost pixel
//
// Usage:
//   for (int row = 0; row < 16; row++) {{
//       uint16_t bits = bitmap[row];
//       for (int col = 0; col < 16; col++) {{
//           uint8_t pixel = (bits >> (15 - col)) & 1;
//           lcd_draw_pixel(x + col, y + row, pixel ? FG : BG);
//       }}
//   }}

#define CJK_CHAR_W  16
#define CJK_CHAR_H  16

"""

def generate_header(chars_data, font_name):
    out = HEADER_TEMPLATE.format(font_name=os.path.basename(font_name))

    for char, cp, pinyin, meaning, rows in chars_data:
        out += f"// {char} (U+{cp:04X}) - {pinyin} / {meaning}\n"
        out += f"static const uint16_t bitmap_char_{cp:04X}[16] = {{\n"
        for i, v in enumerate(rows):
            comma = "," if i < 15 else " "
            bits = "".join("█" if (v >> (15 - b)) & 1 else "·" for b in range(16))
            out += f"    0x{v:04X}{comma}  // {bits}\n"
        out += "};\n\n"

    out += "typedef struct { uint32_t cp; const uint16_t *bmp; const char *name; } CharBitmap;\n\n"
    out += "static const CharBitmap char_bitmaps[] = {\n"
    for char, cp, pinyin, meaning, _ in chars_data:
        out += f'    {{0x{cp:04X}, bitmap_char_{cp:04X}, "{pinyin}"}},  // {char}\n'
    out += "    {0, NULL, NULL}\n"
    out += "};\n\n"

    out += "static inline const uint16_t *get_char_bitmap(uint32_t cp) {\n"
    out += "    for (int i = 0; char_bitmaps[i].cp; i++)\n"
    out += "        if (char_bitmaps[i].cp == cp) return char_bitmaps[i].bmp;\n"
    out += "    return NULL;\n"
    out += "}\n\n"
    out += "#endif // CHAR_BITMAP_H\n"
    return out

def main():
    parser = argparse.ArgumentParser(description="Generate 16x16 CJK bitmaps for ESP32")
    parser.add_argument("--preview", action="store_true")
    parser.add_argument("--threshold", type=int, default=THRESHOLD)
    parser.add_argument("--font", default=None)
    parser.add_argument("--out", default="char_bitmap.h")
    args = parser.parse_args()
    thr = args.threshold

    print("=" * 68)
    print("  CJK 16×16 Bitmap Generator for ESP32 LCD")
    print("=" * 68)

    font_path = args.font or find_font()
    if not font_path:
        print("ERROR: No CJK font found. Pass --font <path>.")
        sys.exit(1)

    print(f"  Font     : {font_path}")
    font = ImageFont.truetype(font_path, OVER_SIZE - 4)
    print(f"  Render   : {OVER_SIZE}×{OVER_SIZE} → {OUT_SIZE}×{OUT_SIZE}  (threshold={thr})")
    print(f"  Output   : {args.out}")
    print()

    chars_data = []
    for char, cp, pinyin, meaning in CHARACTERS:
        try:
            img  = render_char(char, font, thr)
            rows = img_to_uint16_rows(img)
            chars_data.append((char, cp, pinyin, meaning, rows))
            if args.preview:
                print(ascii_preview(img, char))
                print()
            else:
                hex_vals = ", ".join(f"0x{v:04X}" for v in rows)
                print(f"  {char} U+{cp:04X}  {{ {hex_vals} }}")
        except Exception as e:
            print(f"  ERROR on {char}: {e}")

    header = generate_header(chars_data, font_path)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(header)

    print()
    print(f"  Done: {len(chars_data)} characters → {args.out}")
    print("=" * 68)

if __name__ == "__main__":
    main()
