#!/usr/bin/env python3
"""
Generate 12x12 pixel bitmap data for Chinese characters.
This script uses PIL/Pillow to render actual characters from system fonts.
Run this to generate optimized bitmap data specific to your font preference.
"""

import os
import sys
import subprocess

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Installing Pillow...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow", "-q"])
    from PIL import Image, ImageDraw, ImageFont

CHARACTERS = [
    ('气', 0x6C14, "qi"),      # Air
    ('温', 0x6E29, "wen"),     # Temperature
    ('湿', 0x6E7F, "shi"),     # Humidity
    ('度', 0x5EA6, "du"),      # Degree
    ('土', 0x571F, "tu"),      # Soil
    ('光', 0x5149, "guang"),   # Light
    ('照', 0x7167, "zhao"),    # Shine
    ('压', 0x538B, "ya"),      # Pressure
    ('告', 0x544A, "gao"),     # Inform
    ('警', 0x8B66, "jing"),    # Alert
    ('等', 0x7B49, "deng"),    # Etc
    ('待', 0x5F85, "dai"),     # Wait
    ('无', 0x65E0, "wu"),      # None
    ('数', 0x6570, "shu"),     # Number
    ('据', 0x636E, "ju"),      # According
    ('正', 0x6B63, "zheng"),   # Right
    ('常', 0x5E38, "chang"),   # Normal
]

BITMAP_SIZE = 12

def find_font():
    """Find an available CJK font."""
    font_paths = [
        "C:/Windows/Fonts/msyh.ttc",      # Microsoft YaHei (preferred)
        "C:/Windows/Fonts/simhei.ttf",    # SimHei
        "C:/Windows/Fonts/simsun.ttc",    # SimSun
        "C:/Windows/Fonts/NSimSun.ttf",   # NSimSun
    ]
    
    for path in font_paths:
        if os.path.exists(path):
            return path
    
    return None

def render_char(char, font, size=11):
    """Render a character to a 12x12 bitmap."""
    img = Image.new('1', (BITMAP_SIZE, BITMAP_SIZE), color=1)  # White background
    draw = ImageDraw.Draw(img)
    
    try:
        # Get text bounding box to center it
        bbox = draw.textbbox((0, 0), char, font=font)
        if bbox:
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]
        else:
            text_width = text_height = BITMAP_SIZE
        
        # Center the character
        x = (BITMAP_SIZE - text_width) // 2
        y = (BITMAP_SIZE - text_height) // 2
        
        draw.text((x, y), char, font=font, fill=0)  # Black text on white background
    except Exception as e:
        print(f"  Error rendering {char}: {e}")
    
    return img

def convert_bitmap_to_hex(img):
    """Convert PIL image to list of uint16_t hex values."""
    pixels = list(img.getdata())
    result = []
    
    for row in range(BITMAP_SIZE):
        row_pixels = pixels[row * BITMAP_SIZE:(row + 1) * BITMAP_SIZE]
        
        # Pack into uint16_t: bits [15:4] = pixels, bits [3:0] = 0
        val = 0
        for col in range(BITMAP_SIZE):
            pixel = row_pixels[col]
            # Invert: PIL uses 0=black (filled), 1=white (empty)
            bit = 1 if pixel == 0 else 0
            # Shift to position: bit 15 = col 0, bit 4 = col 11
            val |= (bit << (15 - col))
        
        result.append(f"0x{val:04X}")
    
    return result

def main():
    print("="*70)
    print("Chinese Character Bitmap Generator")
    print("="*70)
    print()
    
    # Check and load font
    font_path = find_font()
    if font_path:
        print(f"✓ Found font: {font_path}")
        try:
            font = ImageFont.truetype(font_path, 11)
            print("✓ Font loaded successfully")
        except Exception as e:
            print(f"✗ Could not load font: {e}")
            print("  Using fallback font...")
            try:
                font = ImageFont.truetype("arial.ttf", 11)
            except:
                font = ImageFont.load_default()
    else:
        print("✗ No CJK font found on system")
        print("  Trying fallback fonts...")
        try:
            font = ImageFont.truetype("arial.ttf", 11)
        except:
            font = ImageFont.load_default()
    
    print()
    print(f"Generating bitmaps for {len(CHARACTERS)} characters...")
    print()
    
    # Generate C code
    c_lines = []
    c_lines.append("#ifndef CHAR_BITMAP_H")
    c_lines.append("#define CHAR_BITMAP_H")
    c_lines.append("")
    c_lines.append("#include <stdint.h>")
    c_lines.append("")
    c_lines.append("// Chinese character bitmaps (12x12 pixels)")
    c_lines.append("// Generated by: generate_bitmap.py")
    c_lines.append("// Format: uint16_t array with pixels in bits [15:4]")
    c_lines.append("// MSB (bit 15) = leftmost pixel, bit 4 = rightmost pixel")
    c_lines.append("// Bits [3:0] are always 0")
    c_lines.append("")
    
    for char, code_point, pinyin in CHARACTERS:
        print(f"  {char} (U+{code_point:04X} {pinyin})...", end=" ", flush=True)
        
        try:
            # Render character
            img = render_char(char, font)
            hex_data = convert_bitmap_to_hex(img)
            
            # Generate C array
            c_lines.append(f"// {char} (U+{code_point:04X}) - {pinyin}")
            c_lines.append(f"const uint16_t bitmap_char_{code_point:04X}[] = {{")
            for i, hex_val in enumerate(hex_data):
                if i < len(hex_data) - 1:
                    c_lines.append(f"    {hex_val},")
                else:
                    c_lines.append(f"    {hex_val}")
            c_lines.append("};")
            c_lines.append("")
            
            print("OK")
        except Exception as e:
            print(f"ERROR: {e}")
    
    # Add lookup structure
    c_lines.append("// Bitmap lookup table")
    c_lines.append("typedef struct {")
    c_lines.append("    uint32_t code_point;")
    c_lines.append("    const uint16_t *bitmap;")
    c_lines.append("    const char *name;")
    c_lines.append("} CharBitmap;")
    c_lines.append("")
    c_lines.append("const CharBitmap char_bitmaps[] = {")
    for char, code_point, pinyin in CHARACTERS:
        c_lines.append(f"    {{0x{code_point:04X}, bitmap_char_{code_point:04X}, \"{pinyin}\"}},")
    c_lines.append("    {0, NULL, NULL}")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append("// Helper function to get bitmap")
    c_lines.append("static inline const uint16_t* get_char_bitmap(uint32_t cp) {")
    c_lines.append("    for (int i = 0; char_bitmaps[i].code_point != 0; i++) {")
    c_lines.append("        if (char_bitmaps[i].code_point == cp) return char_bitmaps[i].bitmap;")
    c_lines.append("    }")
    c_lines.append("    return NULL;")
    c_lines.append("}")
    c_lines.append("")
    c_lines.append("#endif // CHAR_BITMAP_H")
    
    # Write output
    output = "\n".join(c_lines)
    with open("char_bitmap.h", "w", encoding="utf-8") as f:
        f.write(output)
    
    print()
    print("="*70)
    print("✓ Generated char_bitmap.h")
    print("="*70)
    
    # Print preview
    print()
    print("Header file preview:")
    print("-"*70)
    for line in output.split('\n')[:60]:
        print(line)
    print("...")
    print("-"*70)

if __name__ == "__main__":
    main()
